# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-07 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='rel_date',
            field=models.DateField(),
        ),
    ]
